// This file is auto-generated by Fresh
import * as $0 from "./routes/index.tsx";
const manifest = { routes: { "./routes/index.tsx": $0 }, islands: {}, baseUrl: import.meta.url };
export default manifest;
